code --install-extension albert.tabout
code --install-extension aykutsarac.jsoncrack-vscode
code --install-extension bobmagicii.autofoldyeah
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension foxundermoon.shell-format
code --install-extension fwcd.kotlin
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension golang.go
code --install-extension gruntfuggly.todo-tree
code --install-extension jock.svg
code --install-extension kevinrose.vsc-python-indent
code --install-extension mathiasfrohlich.kotlin
code --install-extension mechatroner.rainbow-csv
code --install-extension misogi.ruby-rubocop
code --install-extension ms-python.autopep8
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.makefile-tools
code --install-extension mwpb.java-prettier-formatter
code --install-extension pomber.git-file-history
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension stylelint.vscode-stylelint
code --install-extension svelte.svelte-vscode
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vitaliymaz.vscode-svg-previewer
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension yoavbls.pretty-ts-errors
